SELECT PLAYER_NAME, t1.NICKNAME AS HOME_TEAM, t2.NICKNAME AS VISITOR_TEAM, g.SEASON, PTS_home+PTS_away AS PTS_MATCH, PTS, 
       ROUND(PTS/(PTS_home+PTS_away),3) AS P_PTS
FROM games_details2 gd, games2 g, teams2 t1, teams2 t2, players2 p
WHERE gd.GAME_ID=g.GAME_ID AND HOME_TEAM_ID=t1.TEAM_ID AND VISITOR_TEAM_ID=t2.TEAM_ID AND p.PLAYER_ID=gd.PLAYER_ID
      AND (t1.TEAM_ID IN (SELECT r.TEAM_ID FROM ranking2 r WHERE CONFERENCE='West' GROUP BY r.TEAM_ID) 
		     OR t2.TEAM_ID IN (SELECT r.TEAM_ID FROM ranking2 r WHERE CONFERENCE='West' GROUP BY r.TEAM_ID)) AND g.SEASON=2021                                                           
GROUP BY gd.GAME_ID, p.PLAYER_NAME
HAVING P_PTS>0.2