db.games.aggregate([
    {$lookup:{
        from:"teams",
        localField:"HOME_TEAM_ID",
        foreignField:"TEAM_ID",
        as:"teams1"
    }},
    {$lookup:{
        from:"teams",
        localField:"VISITOR_TEAM_ID",
        foreignField:"TEAM_ID",
        as:"teams2"
    }},
    {$unwind:"$teams1"},
    {$unwind:"$teams2"},
    {$project:{"HOME":"$teams1.NICKNAME","OPPONENT":"$teams2.NICKNAME",GAME_DATE_EST:1,PTS_home:1,PTS_away:1,HOME_TEAM_WINS:1,SEASON:1}},
    {$match:{HOME:"Lakers",HOME_TEAM_WINS:true,SEASON:2019}},
    {$project:{OPPONENT:1,GAME_DATE_EST:1,PTS_home:1,PTS_away:1,_id:0}}
])